/* autogenerated by Processing revision 1283 on 2022-07-14 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_4balls_OOPS extends PApplet {

Ball ball1, ball2, ball3, ball4;
final int WIDTH = 750;
final int HEIGHT = 750;
final int radius = 20;
 public void settings() {
  size(WIDTH,HEIGHT);
}

 public void setup(){
  //Sets the value of yposition and interval according to problem statement for each ball.
  ball1 = new Ball(HEIGHT/5,1);
  ball2 = new Ball(2*HEIGHT/5,2);
  ball3 = new Ball(3*HEIGHT/5,3);
  ball4 = new Ball(4*HEIGHT/5,4);
  
}

 public void draw() {
  //Call the function
  ball1.rollball();
  ball2.rollball();
  ball3.rollball();
  ball4.rollball();
}

class Ball{
  int yposition;
  int xposition = 0;
  int interval;
  
  //Constructor to assign the yposition of the ball and the interval. initial xposition is same for all objects.
  Ball(int y, int i){
    yposition = y;
    interval = i;
  }
  
  //Executes the ellipse() function and increments the value of xposition according to interval.
   public void rollball(){
    ellipse(xposition, yposition, radius, radius);
    xposition = xposition + interval;
  }  
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_4balls_OOPS" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
